apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: security-rating
  name: security-rating
  namespace: "development"
spec:
  replicas: 2
  selector:
#    app: security-rating
  template:
    metadata:
      labels:
        app: security-rating
    spec:
#      minReadySeconds: 0
#      revisionHistoryLimit: 1
#      strategy:
#       type: RollingUpdate
#        rollingUpdate:
#          maxSurge: 1
#          maxUnavailable: 1
      imagePullPolicy: Always
      containers:
      - image: cinnojam/security-rating:latest
        name: security-rating
        imagePullPolicy: Always
        ports:
        - containerPort: 8081
          name: backend-http
