apiVersion: v1
kind: Service
metadata:
  labels:
    app: security-rating
  name: security-rating
  namespace: "production"
spec:
  ports:
  - port: 8081
    name: http
    targetPort: backend-http
  selector: 
    app: security-rating
  type: LoadBalancer
